version: '3.8'

services:
  gpu-profiler:
    build: .
    container_name: gpu-profiler
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped 